#!/bin/bash

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

test -e test.png && rm test.png

# Beaker installation and extension
beakerx install
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install beakerx-jupyterlab
conda create -y -n labx 'python>=3'
source activate labx
conda config --env --add pinned_packages 'openjdk>8.0.121'
conda install -y -c conda-forge jupyterlab beakerx

# Git Jupyter Lab extension 
jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git

# Github Jupyter Lab extension
jupyter labextension install @jupyterlab/github

# Draw.io Jupyter Lab extension
jupyter labextension install jupyterlab-drawio

# Rise Jupyter extension (presentation mode)
jupyter-nbextension install rise --py --sys-prefix
jupyter-nbextension enable  rise --py --sys-prefix
jupyter labextension install jupyterlab_rise

# Plotly Jupyter Lab extension
jupyter labextension install @jupyterlab/plotly-extension

# Table of contents Jupyter Lab Extension
jupyter labextension install @jupyterlab/toc

# Latex Jupyter Lab extension
jupyter labextension install @jupyterlab/latex




# Building everything
jupyter lab build


rm conda-bld -R
