#!/bin/bash

conda install -c conda-forge jupyterlab=1.2
beakerx install --lab
beakerx_tabledisplay install --lab
###############################################################
#          jupyter/jupyterlab extensions/kernels              #
###############################################################

# Beaker installation and extension setup
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build

# Table of contents Jupyter Lab Extension
 jupyter labextension install @jupyterlab/toc --no-build
# <error>
# Jupyter/Jupyterlab extension for proxying internal applications
# jupyter serverextension enable --sys-prefix jupyter_server_proxy
# jupyter labextension install jupyterlab-server-proxy --no-build


# Git Jupyter/Lab extension
 jupyter labextension install @jupyterlab/git --no-build
# jupyter serverextension enable --py jupyterlab_git

# Github Jupyter Lab extension
 jupyter labextension install @jupyterlab/github --no-build

# Rise Jupyter extension (presentation mode)
# <error>
# jupyter-nbextension install rise --py --sys-prefix
# jupyter-nbextension enable  rise --py --sys-prefix

# Plotly Jupyter Lab extension
# <error>
# jupyter labextension install @jupyterlab/plotly-extension --no-build

# Building everything up for jupyterlab extensions
jupyter lab build --dev-build=False --minimize=False
